spring:
  application:
    name: AniTrack
  docker:
    compose:
      enabled: false

mal:
  client-id: ${MAL_CLIENT_ID}
  client-secret: ${MAL_CLIENT_SECRET}

application:
  backend-url: ${BACKEND_URL}
  frontend-url: ${FRONTEND_URL}
  in-production: ${IN_PRODUCTION}
